# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ARG_FROM

MAINTAINER Tim Hockin <thockin@google.com>

ADD bin/ARG_ARCH/ARG_BIN /ARG_BIN
ENV GIT_SYNC_DEST /git

RUN apk update --no-cache && apk add \
    ca-certificates \
    coreutils \
    git \
    openssh-client \
    wget

RUN wget -O /sbin/tini https://github.com/krallin/tini/releases/download/v0.14.0/tini-static-ARG_ARCH && \
  chmod +x /sbin/tini

USER nobody:nobody
ENTRYPOINT ["/sbin/tini", "--"]

CMD ["/ARG_BIN"]
