# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM {ARG_FROM}

RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get -y install \
        ca-certificates \
        coreutils \
        socat \
        git \
        openssh-client \
    && rm -rf /var/lib/apt/lists/*

# Run as non-root by default.  There's simply no reason to run as root.
USER 65533:65533

# Add the default UID to /etc/passwd so SSH is satisfied.
RUN echo "git-sync:x:65533:65533::/tmp:/sbin/nologin" >> /etc/passwd
# A user might choose a different UID and set the --add-user flag, which needs
# to be able to write to /etc/passwd.
RUN chmod 0666 /etc/passwd

# Setting HOME ensures that whatever UID this ultimately runs as can write to
# files like ~/.gitconfig.
ENV HOME=/tmp
WORKDIR /tmp

# Just dump the binary in the root.
ADD bin/{ARG_OS}_{ARG_ARCH}/{ARG_BIN} /{ARG_BIN}
ENTRYPOINT ["/{ARG_BIN}"]
