# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM {ARG_FROM}

MAINTAINER Tim Hockin <thockin@google.com>

ADD bin/{ARG_OS}_{ARG_ARCH}/{ARG_BIN} /{ARG_BIN}

RUN apk update --no-cache && apk add \
    ca-certificates \
    coreutils \
    git \
    openssh-client

RUN echo "git-sync:x:65533:65533::/tmp:/sbin/nologin" >> /etc/passwd

# Compile libnss_wrapper (see https://bugs.alpinelinux.org/issues/6710)
RUN apk add --no-cache --virtual .nss_wrapper-build-deps git build-base cmake cmocka-dev && \
    git clone git://git.samba.org/nss_wrapper.git && \
    cd nss_wrapper && \
    mkdir build && \
    cd build/ && \
    mkdir -p /usr/local/include/ && \
    echo -e "#ifndef NSS__H\n#define NSS__H\n\nenum nss_status\n{\n\tNSS_STATUS_TRYAGAIN = -2,\n\tNSS_STATUS_UNAVAIL = -1,\n\tNSS_STATUS_NOTFOUND = 0,\n\tNSS_STATUS_SUCCESS = 1,\n\tNSS_STATUS_RETURN = 2\n};\n\n#endif" > /usr/local/include/nss.h && \
    cmake .. -DUNIT_TESTING:BOOL=ON && \
    make && \
    make CTEST_OUTPUT_ON_FAILURE=TRUE test && \
    make install && \
    rm -fr /nss_wrapper

ADD nss_wrapper.sh /nss_wrapper.sh

WORKDIR /tmp
USER git-sync:nobody
ENTRYPOINT ["/{ARG_BIN}"]
